import { useState, type FormEvent } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Building2, CheckCircle2, Clock3, Plus, ShieldCheck } from 'lucide-react';
import { useAuth } from '../auth/AuthContext';
import { getCompany,inviteAdmin,revokeAdmin,invitationState,reviewInstitutionApplication,type InstitutionApplication,type ReadyInvitation } from './api';
import { InvitationReceipt } from './InvitationReceipt';
import '../office/office.css';
import './onboarding.css';

import { normalizeInstitutionCode } from './institution-code';
import { CreateInstitution } from '../institutions/CreateInstitution';
import { useParams } from 'react-router-dom';
import '../institutions/institutions.css';

export default function CompanyPage() {
  const auth=useAuth();const query=useQuery({queryKey:['company','institutions'],queryFn:getCompany});
  const [creating,setCreating]=useState(false);const [invite,setInvite]=useState<ReadyInvitation|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [search,setSearch]=useState('');
  const { id: institutionId } = useParams();
  const [reviewing,setReviewing]=useState<InstitutionApplication|null>(null);const [reviewAction,setReviewAction]=useState<'request_information'|'approve'|'reject'>('approve');const [reviewNote,setReviewNote]=useState('');const [approvalCode,setApprovalCode]=useState('');
  function openCreator(){setError('');setCreating(true);}
  async function admin(event:FormEvent<HTMLFormElement>) {
    event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError('');
    const schoolId=form.get('school_id');const email=form.get('email');
    try{if(typeof schoolId!=='string'||typeof email!=='string')throw new Error('Administrator invitation details are invalid.');setInvite(await inviteAdmin(schoolId,email));await query.refetch();}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}
  }
  function openReview(application:InstitutionApplication){setReviewing(application);setReviewAction('approve');setReviewNote('');setApprovalCode(application.requested_code);setError('');}
  async function review(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!reviewing)return;setBusy(true);setError('');try{await reviewInstitutionApplication(reviewing.id,{action:reviewAction,note:reviewNote,...(reviewAction==='approve'?{institution_code:normalizeInstitutionCode(approvalCode)}:{})});setReviewing(null);await query.refetch();}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
  return <main className="company-console"><header className="company-top"><a href="/company" className="company-brand"><ShieldCheck/>Eduera <span>Company console</span></a><div><span>{auth.user?.display_name}</span><button className="office-secondary" onClick={()=>void auth.logout()}>Sign out</button></div></header><div className="office-page">
    <header className="company-title"><div><h1>Institutions</h1><p>Create a school or college and hand setup to its administrator.</p></div><button className="office-primary" disabled={busy} onClick={openCreator}><Plus size={16}/>Create institution</button></header>
    <ol className="institution-onboarding-steps" aria-label="Institution onboarding"><li><strong>1. Company provisions</strong><span>Create institution and admin invitation.</span></li><li><strong>2. Admin activates</strong><span>Accept the code and sign in.</span></li><li><strong>3. School takes over</strong><span>Set up terms, invite people and delegate roles.</span></li></ol>
    {error?<p className="office-alert" role="alert">{error}</p>:null}{invite?<InvitationReceipt invite={invite} onClose={()=>setInvite(null)}/>:null}
    {reviewing?<form className="office-panel office-form company-review-form" onSubmit={event=>void review(event)}><div className="company-title"><div><span className="company-section-label">Application review</span><h2>{reviewing.institution_name}</h2><p>{reviewing.institution_kind} · {reviewing.district}, {reviewing.state_code}</p></div><button type="button" className="office-secondary" onClick={()=>setReviewing(null)}>Close</button></div><dl className="company-application-details"><div><dt>Applicant</dt><dd>{reviewing.first_name} {reviewing.last_name}<small>{reviewing.applicant_email}</small></dd></div><div><dt>Authority</dt><dd>{reviewing.applicant_role_title}</dd></div><div><dt>Reference</dt><dd>{reviewing.regulator_type.replaceAll('_',' ')}<small>{reviewing.regulator_reference}</small></dd></div><div><dt>Website</dt><dd>{reviewing.website||'Not provided'}</dd></div></dl><fieldset disabled={busy} className="onboarding-fields"><label className="office-field">Decision<select value={reviewAction} onChange={event=>setReviewAction(event.target.value as typeof reviewAction)}><option value="approve">Approve and provision workspace</option><option value="request_information">Request more information</option><option value="reject">Reject application</option></select></label>{reviewAction==='approve'?<label className="office-field">Institution code<input value={approvalCode} onChange={event=>setApprovalCode(event.target.value)} onBlur={()=>setApprovalCode(normalizeInstitutionCode(approvalCode))} required minLength={2} maxLength={32}/></label>:null}<label className="office-field">Review note<textarea rows={3} value={reviewNote} onChange={event=>setReviewNote(event.target.value)} required={reviewAction!=='approve'} placeholder={reviewAction==='approve'?'Optional internal handoff note':'Explain what the applicant needs to do next'}/></label><p className="office-hint">Approval creates the institution tenant and grants the applicant its first administrator membership. Company operators still receive no student-record access.</p><div className="office-actions"><button type="button" className="office-secondary" onClick={()=>setReviewing(null)}>Cancel</button><button className="office-primary" disabled={busy}>{busy?'Saving decision…':reviewAction==='approve'?'Approve & create workspace':reviewAction==='reject'?'Reject application':'Send information request'}</button></div></fieldset></form>:null}
    {creating?<section className="office-panel institution-panel"><CreateInstitution onCreated={result=>{setInvite(result.invitation);setCreating(false);void query.refetch();}} onCancel={()=>setCreating(false)}/></section>:null}
    {query.isPending?<p role="status">Loading institutions…</p>:query.isError?<section className="office-panel"><p role="alert">{query.error.message}</p><button className="office-secondary" onClick={()=>void query.refetch()}>Retry</button></section>:query.data?<>
      <section className="office-panel company-application-queue"><div className="company-title"><div><span className="company-section-label">Verification queue</span><h2>Institution applications</h2><p>Only approval provisions a tenant and administrator access.</p></div><span className="office-status">{(query.data.applications??[]).filter(application=>application.status==='submitted').length} waiting</span></div><div className="company-application-list">{(query.data.applications??[]).map(application=><article key={application.id}><div className="company-application-list__icon">{application.status==='approved'?<CheckCircle2/>:<Clock3/>}</div><div><strong>{application.institution_name}</strong><span>{application.institution_kind} · {application.district}, {application.state_code}</span><small>{application.first_name} {application.last_name} · {application.applicant_email}</small></div><span className={`company-application-state company-application-state--${application.status}`}>{application.status.replace('_',' ')}</span>{['submitted','needs_information'].includes(application.status)?<button type="button" className="office-secondary" onClick={()=>openReview(application)}>{application.status==='submitted'?'Review':'Open'}</button>:null}</article>)}</div>{!(query.data.applications??[]).length?<p>No institution applications are waiting yet.</p>:null}</section>
      {institutionId?<a href="/company">View all institutions</a>:null}<label className="office-field">Find institution<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or code"/></label><div className="institution-list">{query.data.schools.filter(s=>(!institutionId||s.id===institutionId)&&(s.name+' '+s.code).toLowerCase().includes(search.toLowerCase())).map(s=><article className="office-panel" key={s.id}><div className="company-title"><div><h2><Building2 size={18}/>{s.name}</h2><p>{s.institution_kind} · {s.code}</p></div><span className="office-status">{s.onboarding_status==='suspended'?'Suspended':s.onboarding_status==='active'?'Active':s.onboarding_status==='setup_in_progress'?'Setup in progress':s.admin_count?'Active':'Awaiting admin'}</span></div><p>{s.admin_count} active administrators · {s.pending_admins} pending admin invitations</p><details open={Boolean(institutionId)}><summary>Invite or replace administrator invitation</summary><form className="office-form" onSubmit={event=>void admin(event)}><input type="hidden" name="school_id" value={s.id}/><label className="office-field">Administrator email<input type="email" name="email" required disabled={busy}/></label><button className="office-secondary" disabled={busy}>{busy?'Creating…':'Create admin invitation'}</button></form></details></article>)}</div>
      {!query.data.schools.length?<p>No institutions yet. Create the first school or college.</p>:!query.data.schools.some(s=>(s.name+' '+s.code).toLowerCase().includes(search.toLowerCase()))?<p>No matching institutions.</p>:null}
      <section className="office-panel"><h2>Admin invitations</h2><ul className="office-list office-list--cards">{query.data.invitations.map(i=><li key={i.id}><div><strong>{i.school_name}</strong><span>{i.email}</span><small>Expires {new Date(i.expires_at).toLocaleString()}</small></div><span>{invitationState(i)}</span>{invitationState(i)==='Pending'?<button disabled={busy} onClick={()=>{setBusy(true);setError('');void revokeAdmin(i.school_id!,i.id).then(()=>query.refetch()).catch(cause=>setError((cause as Error).message)).finally(()=>setBusy(false));}}>Revoke</button>:null}</li>)}</ul>{!query.data.invitations.length?<p>No admin invitations created yet.</p>:null}</section>
    </>:null}
  </div></main>;
}
