import {useEffect,useRef,useState} from "react";
import {searchGuardians,type GuardianChoice} from "./api";
import {updateImportRow,type ImportDetail,type ImportRow,type ImportValues} from "./import-api";
const labels:Record<keyof ImportValues,string>={admission_number:"Admission number",first_name:"Student first name",last_name:"Student last name",date_of_birth:"Date of birth",class:"Class",roll_number:"Roll number",enrolled_on:"Enrolled from",guardian_key:"Family reference",guardian_first_name:"Guardian first name",guardian_last_name:"Guardian last name",guardian_phone:"Guardian phone",guardian_email:"Guardian email",relationship:"Relationship"};
export function ImportRowEditor({schoolId,job,row,onClose,onSaved}:{schoolId:string;job:ImportDetail;row:ImportRow;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [values,setValues]=useState(row.values);const [decision,setDecision]=useState(row.decision);const [choice,setChoice]=useState(row.guardian_choice);
  const [revision]=useState(job.revision);const stale=revision!==job.revision;
  const [search,setSearch]=useState("");const [choices,setChoices]=useState<GuardianChoice[]>([]);const [searched,setSearched]=useState(false);const [searching,setSearching]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{heading.current?.focus();},[]);
  async function find(){setError("");setSearching(true);try{setChoices((await searchGuardians(schoolId,search)).results);setSearched(true);}catch(e){setError(e instanceof Error?e.message:"Guardian search failed.");}finally{setSearching(false);}}
  async function save(){if(busy||stale)return;setBusy(true);setError("");try{await updateImportRow(job.id,row.row_number,{school_id:schoolId,expected_revision:revision,values,decision,guardian_choice:choice});await onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:"Could not save this row.");}finally{setBusy(false);}}
  const field=(key:keyof ImportValues,type="text")=><label key={key}>{labels[key]}<input type={type} value={values[key]} maxLength={500} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>;
  return <section className="people-panel import-editor" aria-labelledby="import-row-title"><header className="people-heading"><div><h2 ref={heading} tabIndex={-1} id="import-row-title">Review row {row.row_number}</h2><p className="people-muted">{row.values.first_name} {row.values.last_name} · {row.values.admission_number}</p></div><button className="people-secondary" disabled={busy} onClick={onClose}>Cancel edit</button></header>
    {error?<p role="alert" className="people-error">{error}</p>:null}
    {stale?<p role="alert" className="people-error">The draft changed while you were editing. Cancel this edit and open the latest row before saving.</p>:null}
    <form className="people-form" onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} className="people-fieldset">
      <label>Include this student<select value={decision} onChange={e=>setDecision(e.target.value as "include"|"skip")}><option value="include">Include in import</option><option value="skip">Skip this row</option></select></label>
      {decision==='include'?<>
        <div className="people-form-grid">{field("admission_number")}{field("first_name")}{field("last_name")}{field("date_of_birth","date")}<label>Class<select value={values.class.replace(/^Class /i,"")} onChange={e=>setValues({...values,class:e.target.value})}><option value={values.class}>{values.class||"Choose class"}</option>{job.review?.classes.filter(c=>c.label!==values.class).map(c=><option key={c.id} value={c.label}>{c.label}</option>)}</select></label>{field("roll_number","number")}{field("enrolled_on","date")}<label>Relationship<select value={values.relationship} onChange={e=>setValues({...values,relationship:e.target.value})}><option value={values.relationship}>{values.relationship||"Choose relationship"}</option>{['mother','father','guardian'].filter(r=>r!==values.relationship).map(r=><option key={r} value={r}>{r}</option>)}</select></label></div>
        <h3>Guardian record</h3><label>Guardian choice<select value={choice.mode} onChange={e=>setChoice(e.target.value==='new'?{mode:'new'}:{mode:'existing',id:''})}><option value="new">Create from this row</option><option value="existing">Link a verified school guardian</option></select></label>
        {field("guardian_key")}<p className="people-muted">Use the same family reference only for the same person. All included rows with that reference must agree.</p>
        {choice.mode==='new'?<div className="people-form-grid">{field("guardian_first_name")}{field("guardian_last_name")}{field("guardian_phone","tel")}{field("guardian_email","email")}</div>:<div className="people-guardian-search"><label>Find existing guardian<input value={search} maxLength={80} onChange={e=>setSearch(e.target.value)}/></label><button type="button" className="people-secondary" disabled={search.trim().length<2||searching} onClick={()=>void find()}>{searching?"Searching…":"Search guardians"}</button>{choices.length?<label>Select the verified guardian<select value={choice.id} onChange={e=>setChoice({mode:'existing',id:e.target.value})}><option value="">Choose a guardian</option>{choices.map(g=><option key={g.id} value={g.id}>{g.name} · {g.phone} · {g.linked_admissions}</option>)}</select></label>:searched?<p>No guardians match. Try another name or phone.</p>:choice.id?<p className="people-muted">Current selection: {row.guardian_name}</p>:null}</div>}
      </>:<p className="people-muted">This row will be excluded. Nothing will be created or changed for this student.</p>}
    </fieldset><button className="people-primary" disabled={busy||stale||(decision==='include'&&choice.mode==='existing'&&!choice.id)}>{busy?"Saving row…":"Save & recheck"}</button></form>
  </section>;
}
