import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bus, Check, CircleAlert, LocateFixed, MapPin, Navigation, Power, Repeat2, Square } from "lucide-react";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { OperationsShell } from "../../pages/operations/OperationsShell";
import { useAuth } from "../auth/AuthContext";
import { LiveRouteError, ScreenLoading } from "../school/LiveRouteState";
import { getCollectorDeparture, requestDutySwap, respondDutySwap, sendTripLocation, tripAction, updateRider } from "./api";
import { LiveMap } from "./LiveMap";
import "./departure.css";

type WakeSentinel={release:()=>Promise<void>;addEventListener:(name:"release",listener:()=>void)=>void};
const formValue=(form:FormData,key:string)=>{const value=form.get(key);return typeof value==="string"?value.trim():"";};

export default function CollectorJourneyPage(){
  const auth=useAuth();const client=useQueryClient();const query=useQuery({queryKey:["departure","collector"],queryFn:getCollectorDeparture,refetchInterval:15_000});
  const [selected,setSelected]=useState("");const [tracking,setTracking]=useState(false);const [trackingMessage,setTrackingMessage]=useState("");const [error,setError]=useState("");const [showSwap,setShowSwap]=useState(false);const [swapType,setSwapType]=useState<"cover"|"exchange">("cover");const [targetUser,setTargetUser]=useState("");
  const watch=useRef<number|null>(null);const wake=useRef<WakeSentinel|null>(null);const lastSent=useRef(0);
  const mutation=useMutation({mutationFn:async(fn:()=>Promise<unknown>)=>fn(),onSuccess:async()=>{setError("");await client.invalidateQueries({queryKey:["departure"]});},onError:cause=>setError(cause instanceof Error?cause.message:"Journey could not be updated.")});
  const data=query.data;const trip=data?.trips.find(item=>item.id===selected)||data?.trips.find(item=>["boarding","in_progress"].includes(item.state))||data?.trips[0];

  const submitSwap=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!trip)return;const form=new FormData(event.currentTarget);mutation.mutate(()=>requestDutySwap({requester_trip_id:trip.id,request_type:swapType,target_user_id:formValue(form,"target_user"),target_trip_id:swapType==="exchange"?formValue(form,"target_trip"):null,reason:formValue(form,"reason")}),{onSuccess:()=>setShowSwap(false)});};

  const stopTracking=async()=>{if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;setTracking(false);setTrackingMessage("");if(wake.current)await wake.current.release().catch(()=>undefined);wake.current=null;};
  useEffect(()=>()=>{if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);void wake.current?.release();},[]);

  async function startTracking(){
    if(!trip||trip.state!=="in_progress")return; if(!navigator.geolocation){setError("This device does not support location sharing.");return;}
    try { const n=navigator as Navigator&{wakeLock?:{request:(kind:"screen")=>Promise<WakeSentinel>}}; if(n.wakeLock){wake.current=await n.wakeLock.request("screen");wake.current.addEventListener("release",()=>setTrackingMessage("Screen wake lock was released. Keep this page visible."));} } catch { setTrackingMessage("Keep this screen open and prevent the phone from locking."); }
    watch.current=navigator.geolocation.watchPosition(position=>{
      const now=Date.now();if(now-lastSent.current<10_000)return;lastSent.current=now;setTracking(true);setTrackingMessage("Location sharing is active. Keep this journey screen open.");
      void sendTripLocation(trip.id,{latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy_metres:position.coords.accuracy,heading_degrees:position.coords.heading!==null&&Number.isFinite(position.coords.heading)?position.coords.heading:null,speed_metres_per_second:position.coords.speed!==null&&Number.isFinite(position.coords.speed)?position.coords.speed:null,observed_at:new Date(position.timestamp).toISOString()}).then(()=>client.invalidateQueries({queryKey:["departure","collector"]})).catch(cause=>setError(cause instanceof Error?cause.message:"Location update failed."));
    },locationError=>{setTracking(false);setTrackingMessage(locationError.code===1?"Location permission was denied. Enable it in browser settings.":"Location is temporarily unavailable. Keep this screen open.");},{enableHighAccuracy:true,maximumAge:5_000,timeout:15_000});
  }

  if(query.isPending)return <ScreenLoading/>;if(query.error||!data)return <LiveRouteError error={query.error??new Error("Assigned journeys are unavailable.")} onRetry={query.refetch}/>;
  const location=trip?.latest_location?{lat:Number(trip.latest_location.latitude),lng:Number(trip.latest_location.longitude),accuracy:Number(trip.latest_location.accuracy_metres)}:null;
  return <OperationsShell portal="teacher" active="more" title="Transport journey" schoolName={trip?.school_name??auth.memberships.find(item=>item.role==="staff")?.school_name} backTo="/teacher/more"><div className="departure-page departure-page--collector">
    {!trip?<section className="departure-panel departure-empty"><Bus size={28}/><h2>No assigned journey</h2><p>An administrator must assign you as collector on a dated trip.</p></section>:<>
      {data.trips.length>1?<label className="departure-trip-picker">Journey<select value={trip.id} onChange={event=>setSelected(event.target.value)}>{data.trips.map(item=><option value={item.id} key={item.id}>{item.service_date} · {item.route_name}</option>)}</select></label>:null}
      <section className="departure-status"><div><span>{trip.service_date} · {trip.route_code}</span><h2>{trip.route_name}</h2><p>{trip.vehicle_label||trip.provider_name||trip.direction.replaceAll("_"," ")}</p></div><span className={`departure-state departure-state--${trip.state}`}><Bus/>{trip.state.replaceAll("_"," ")}</span></section>

      {trip.collector_assignment_status!=="accepted"?<section className="departure-panel departure-assignment-response"><header><div><span>Duty assignment</span><h2>{trip.collector_assignment_status==="pending"?"Confirm this journey":"Assignment declined"}</h2></div><span className={`departure-state departure-state--${trip.collector_assignment_status}`}>{trip.collector_assignment_status}</span></header>{trip.collector_assignment_status==="pending"?<div><p>Review the date, route and roster before accepting responsibility.</p><button type="button" disabled={mutation.isPending} onClick={()=>mutation.mutate(()=>tripAction(trip.id,"decline",trip.revision,"Unable to cover this journey"))}>Decline</button><button type="button" className="departure-primary" disabled={mutation.isPending} onClick={()=>mutation.mutate(()=>tripAction(trip.id,"accept",trip.revision,"Duty reviewed and accepted"))}><Check/>Accept duty</button></div>:<p className="departure-warning">School operations must assign another collector before this trip can start.</p>}</section>:null}

      {data.swaps.some(swap=>swap.target_user_id===auth.user?.id&&swap.status==="submitted")?<section className="departure-panel"><header><div><span>Needs response</span><h2>Duty change requests</h2></div><Repeat2/></header><div className="departure-swap-queue">{data.swaps.filter(swap=>swap.target_user_id===auth.user?.id&&swap.status==="submitted").map(swap=><article key={swap.id}><Repeat2/><div><strong>{swap.requester_name} requests {swap.request_type}</strong><small>{swap.requester_route_name} · {swap.requester_service_date}{swap.target_route_name?` ↔ ${swap.target_route_name}`:""}</small><p>{swap.reason}</p></div><div><button type="button" onClick={()=>mutation.mutate(()=>respondDutySwap(swap.id,{decision:"rejected",expected_revision:swap.revision,note:"Unable to take this duty"}))}>Decline</button><button type="button" className="departure-primary" onClick={()=>mutation.mutate(()=>respondDutySwap(swap.id,{decision:"accepted",expected_revision:swap.revision,note:"Duty change accepted for school approval"}))}>Accept</button></div></article>)}</div></section>:null}

      {trip.state==="planned"&&trip.collector_assignment_status==="accepted"?<section className="departure-panel departure-duty-change"><header><div><span>Responsibility</span><h2>Duty change</h2></div><button type="button" onClick={()=>setShowSwap(value=>!value)}><Repeat2/>{showSwap?"Close":"Request change"}</button></header>{showSwap?<form className="departure-form" onSubmit={submitSwap}><label>Change type<select value={swapType} onChange={event=>setSwapType(event.target.value as "cover"|"exchange")}><option value="cover">Colleague covers my trip</option><option value="exchange">Exchange two trips</option></select></label><label>Colleague<select name="target_user" required value={targetUser} onChange={event=>setTargetUser(event.target.value)}><option value="">Choose colleague</option>{data.colleagues.filter(person=>person.school_id===trip.school_id).map(person=><option value={person.id} key={person.id}>{person.name}</option>)}</select></label>{swapType==="exchange"?<label className="departure-span">Their trip<select name="target_trip" required><option value="">Choose trip</option>{data.swap_candidates.filter(item=>item.assigned_collector_user_id===targetUser).map(item=><option value={item.id} key={item.id}>{item.service_date} · {item.route_name} · {item.scheduled_departure_time.slice(0,5)}</option>)}</select></label>:null}<label className="departure-span">Reason<textarea name="reason" rows={2} minLength={3} maxLength={500} required/></label><button className="departure-primary" disabled={mutation.isPending}>Send to colleague</button></form>:data.swaps.some(swap=>swap.requester_trip_id===trip.id&&["submitted","accepted"].includes(swap.status))?<p className="departure-pending"><Repeat2/>A duty change is awaiting {data.swaps.find(swap=>swap.requester_trip_id===trip.id)?.status==="submitted"?"your colleague":"school approval"}.</p>:null}</section>:null}

      <section className="departure-panel departure-tracking"><header><div><span>Collector phone</span><h2>Journey location</h2></div><LocateFixed size={22}/></header>
        {location?<LiveMap latitude={location.lat} longitude={location.lng} accuracy={location.accuracy} tileUrl={data.map.tile_url} attribution={data.map.attribution}/>:<div className="departure-map-empty"><MapPin/><strong>No location shared yet</strong></div>}
        {trip.state==="in_progress"?<div className="departure-tracking-controls"><button type="button" className="departure-primary" disabled={tracking} onClick={()=>void startTracking()}><Navigation size={17}/>{tracking?"Sharing location":"Start location sharing"}</button>{tracking?<button type="button" onClick={()=>void stopTracking()}><Square size={15}/>Pause</button>:null}</div>:null}
        {trackingMessage?<p className={tracking?"departure-live-note":"departure-warning"}><span className={tracking?"departure-live-dot":""}/>{trackingMessage}</p>:null}
        <p className="departure-privacy-note">Location is used only for this assigned journey. Families see it only while their own learner is on board.</p>
      </section>

      <section className="departure-panel"><header><div><span>Trip control</span><h2>{trip.roster.length} riders</h2></div><Power size={21}/></header><div className="departure-trip-controls">
        {trip.state==="planned"&&trip.collector_assignment_status==="accepted"?<button className="departure-primary" onClick={()=>mutation.mutate(()=>tripAction(trip.id,"boarding",trip.revision))}>Open boarding</button>:null}
        {trip.state==="boarding"?<button className="departure-primary" onClick={()=>mutation.mutate(()=>tripAction(trip.id,"start",trip.revision))}>Depart and begin journey</button>:null}
        {trip.state==="in_progress"?<button disabled={trip.roster.some(item=>["expected","boarded","exception"].includes(item.state))} onClick={()=>mutation.mutate(async()=>{await stopTracking();return tripAction(trip.id,"complete",trip.revision);})}>Complete trip</button>:null}
      </div>{error?<p className="departure-error" role="alert">{error}</p>:null}</section>

      <section className="departure-panel"><header><div><span>Frozen roster</span><h2>Stops and riders</h2></div><b>{trip.roster.filter(item=>item.state==="dropped").length}/{trip.roster.length}</b></header><div className="departure-rider-list">{trip.roster.map(rider=><article key={rider.student_id}><div className="departure-rider-stop"><span>{rider.stop_sequence}</span><div><strong>{rider.student_name}</strong><small>{rider.stop_name}{rider.planned_time?` · ${rider.planned_time.slice(0,5)}`:""}</small></div></div><span className={`departure-state departure-state--${rider.state}`}>{rider.state.replaceAll("_"," ")}</span><div className="departure-rider-actions">
          {rider.state==="expected"?<><button onClick={()=>mutation.mutate(()=>updateRider(trip.id,rider.student_id,{state:"not_riding",expected_revision:rider.revision,note:"Not riding"}))}>Not riding</button><button className="departure-primary" onClick={()=>mutation.mutate(()=>updateRider(trip.id,rider.student_id,{state:"boarded",expected_revision:rider.revision,note:"Boarded with assigned collector"}))}><Check size={15}/>Boarded</button></>:null}
          {rider.state==="boarded"?<><button onClick={()=>mutation.mutate(()=>updateRider(trip.id,rider.student_id,{state:"exception",expected_revision:rider.revision,note:"Collector flagged an exception"}))}><CircleAlert size={15}/>Exception</button><button className="departure-primary" onClick={()=>mutation.mutate(()=>updateRider(trip.id,rider.student_id,{state:"dropped",expected_revision:rider.revision,note:"Drop-off completed"}))}>Dropped</button></>:null}
          {rider.state==="exception"?<button className="departure-primary" onClick={()=>mutation.mutate(()=>updateRider(trip.id,rider.student_id,{state:"dropped",expected_revision:rider.revision,note:"Exception resolved and drop-off completed"}))}>Resolve & drop</button>:null}
        </div></article>)}</div></section>
    </>}
  </div></OperationsShell>;
}
