import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bus, CheckCircle2, ChevronRight, Clock3, MapPin, Route, ShieldCheck, UserRoundCheck } from "lucide-react";
import { useState, type FormEvent } from "react";
import { OperationsShell } from "../../pages/operations/OperationsShell";
import { useAuth } from "../auth/AuthContext";
import { LiveRouteError, ScreenLoading } from "../school/LiveRouteState";
import { assignTransportStudent, createDepartureAuthority, createDeparturePlan, createTransportRoute, createTransportTrip, decideDepartureRequest, departurePlanAction, getDepartureWorkspace, recordDepartureHandover, recordOfficeDepartureRequest, revokeDepartureAuthority, saveDeparturePolicy, type DepartureMode } from "./api";
import { TransportDutyPlanner } from "./TransportDutyPlanner";
import "./departure.css";

const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata"}).format(new Date());
const value=(form:FormData,key:string)=>{const entry=form.get(key);return typeof entry==="string"?entry.trim():"";};
const modeLabel=(mode:DepartureMode)=>({guardian_pickup:"Guardian pickup",authorized_collector:"Authorized collector",independent_departure:"Independent departure",school_transport:"School bus",external_transport:"External transport"}[mode]);

export default function PrincipalDeparturePage(){
  const auth=useAuth(); const member=auth.memberships.find(item=>item.role==="admin"); const schoolId=member?.school_id??""; const client=useQueryClient();
  const query=useQuery({queryKey:["departure","admin",schoolId],queryFn:()=>getDepartureWorkspace(schoolId),enabled:Boolean(schoolId),refetchInterval:15_000});
  const [panel,setPanel]=useState<"policy"|"route"|"assign"|"trip"|"authority"|"plan"|"office"|null>(null); const [error,setError]=useState("");
  const run=useMutation({mutationFn:async(fn:()=>Promise<unknown>)=>fn(),onSuccess:async()=>{setPanel(null);setError("");await client.invalidateQueries({queryKey:["departure"]});},onError:cause=>setError(cause instanceof Error?cause.message:"The change could not be saved.")});
  if(!schoolId)return <LiveRouteError error={new Error("Institution administrator access is required.")} onRetry={auth.refresh}/>; if(query.isPending)return <ScreenLoading/>; if(query.error||!query.data)return <LiveRouteError error={query.error??new Error("Departure operations are unavailable.")} onRetry={query.refetch}/>;
  const data=query.data; const activeTrips=data.trips.filter(item=>["boarding","in_progress"].includes(item.state));
  const submitRoute=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);const names=value(f,"stops").split("\n").map(item=>item.trim()).filter(Boolean);run.mutate(()=>createTransportRoute(schoolId,{code:value(f,"code"),name:value(f,"name"),vehicle_label:value(f,"vehicle_label"),provider_name:value(f,"provider_name"),service_kind:value(f,"service_kind"),stops:names.map((name,index)=>({direction:value(f,"direction"),sequence:index+1,name}))}));};
  return <OperationsShell portal="principal" active="more" title="Departure & transport" schoolName={data.school.name} backTo="/principal/more"><main className="departure-page departure-page--ops">
    <section className="departure-ops-summary"><div><span>Today</span><strong>{activeTrips.length}</strong><small>active trips</small></div><div><span>Review</span><strong>{data.requests.length}</strong><small>change requests</small></div><div><span>Plans</span><strong>{data.plans.length}</strong><small>next 7 days</small></div></section>

    {data.requests.length?<section className="departure-panel"><header><div><span>Needs decision</span><h2>Departure changes</h2></div><b>{data.requests.length}</b></header><div className="departure-request-list">{data.requests.map(request=><article key={request.id}><div><strong>{request.student_name}</strong><span>{request.service_date} · {modeLabel(request.requested_mode)}</span><p>{request.reason}</p></div><div><button type="button" disabled={run.isPending} onClick={()=>run.mutate(()=>decideDepartureRequest(schoolId,request.id,{decision:"rejected",expected_revision:request.revision,note:"Arrangement not approved"}))}>Decline</button><button type="button" className="departure-primary" disabled={run.isPending} onClick={()=>run.mutate(()=>decideDepartureRequest(schoolId,request.id,{decision:"approved",expected_revision:request.revision,note:"Verified by school operations"}))}>Approve</button></div></article>)}</div></section>:null}

    <TransportDutyPlanner schoolId={schoolId} data={data}/>

    <section className="departure-panel"><header><div><span>Operations</span><h2>Routes and journeys</h2></div><Bus size={22}/></header><div className="departure-action-grid">
      <button onClick={()=>setPanel("policy")}><ShieldCheck/><span><strong>Departure policy</strong><small>Modes, cutoff and privacy</small></span><ChevronRight/></button>
      <button onClick={()=>setPanel("route")}><Route/><span><strong>New route</strong><small>Stops and vehicle</small></span><ChevronRight/></button>
      <button onClick={()=>setPanel("assign")} disabled={!data.routes.length}><UserRoundCheck/><span><strong>Assign learner</strong><small>Route and stop</small></span><ChevronRight/></button>
      <button onClick={()=>setPanel("trip")} disabled={!data.routes.length}><Bus/><span><strong>Create trip</strong><small>Freeze dated roster</small></span><ChevronRight/></button>
      <button onClick={()=>setPanel("authority")}><ShieldCheck/><span><strong>Verify collector</strong><small>Purpose-specific authority</small></span><ChevronRight/></button>
      <button onClick={()=>setPanel("plan")}><Clock3/><span><strong>Set departure plan</strong><small>Pickup or independent</small></span><ChevronRight/></button>
      <button onClick={()=>setPanel("office")}><Clock3/><span><strong>Record assisted request</strong><small>Phone, paper or in person</small></span><ChevronRight/></button>
    </div></section>

    {panel?<section className="departure-panel departure-editor"><header><div><span>Setup</span><h2>{panel==="policy"?"Departure policy":panel==="route"?"Create transport route":panel==="assign"?"Assign learner to route":panel==="trip"?"Create dated trip":panel==="authority"?"Verify collection authority":panel==="office"?"Record assisted request":"Set dated departure plan"}</h2></div><button onClick={()=>setPanel(null)} aria-label="Close">×</button></header>
      {panel==="policy"?<PolicyForm data={data} submit={payload=>run.mutate(()=>saveDeparturePolicy(schoolId,payload))}/>:null}
      {panel==="route"?<form className="departure-form" onSubmit={submitRoute}><label>Route code<input name="code" required maxLength={32}/></label><label>Route name<input name="name" required maxLength={120}/></label><label>Direction<select name="direction"><option value="from_institution">From institution</option><option value="to_institution">To institution</option></select></label><label>Service<select name="service_kind"><option value="institution_managed">Institution managed</option><option value="contracted">Contracted</option></select></label><label>Vehicle<input name="vehicle_label" placeholder="Bus 14 · DL 01 AB 1234"/></label><label>Provider<input name="provider_name" placeholder="School or contractor"/></label><label className="departure-span">Stops, one per line<textarea name="stops" required minLength={2} rows={5}/></label><button className="departure-primary" disabled={run.isPending}>Create route</button></form>:null}
      {panel==="assign"?<form className="departure-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run.mutate(()=>assignTransportStudent(schoolId,{student_id:value(f,"student_id"),route_id:value(f,"route_id"),stop_id:value(f,"stop_id"),direction:value(f,"direction"),valid_from:value(f,"valid_from")}));}}><label>Learner<select name="student_id">{data.students.map(item=><option value={item.id} key={item.id}>{item.name} · {item.admission_number}</option>)}</select></label><label>Route<select name="route_id">{data.routes.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Stop<select name="stop_id">{data.routes.flatMap(item=>item.stops).map(item=><option value={item.id} key={item.id}>{item.name} · {item.direction.replaceAll("_"," ")}</option>)}</select></label><label>Direction<select name="direction"><option value="from_institution">From institution</option><option value="to_institution">To institution</option></select></label><label>Starts<input name="valid_from" type="date" defaultValue={today()} required/></label><button className="departure-primary">Assign learner</button></form>:null}
      {panel==="trip"?<form className="departure-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run.mutate(()=>createTransportTrip(schoolId,{route_id:value(f,"route_id"),service_date:value(f,"service_date"),direction:value(f,"direction"),scheduled_departure_time:value(f,"departure_time"),assigned_collector_user_id:value(f,"collector"),backup_collector_user_id:value(f,"backup")||null}));}}><label>Route<select name="route_id">{data.routes.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Date<input name="service_date" type="date" defaultValue={today()} required/></label><label>Direction<select name="direction"><option value="from_institution">From institution</option><option value="to_institution">To institution</option></select></label><label>Departure time<input name="departure_time" type="time" defaultValue="15:30" required/></label><label>Assigned collector<select name="collector">{data.collectors.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Backup collector<select name="backup"><option value="">No backup</option>{data.collectors.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><button className="departure-primary">Create trip and roster</button></form>:null}
      {panel==="authority"?<AuthorityForm data={data} submit={payload=>run.mutate(()=>createDepartureAuthority(schoolId,payload))}/>:null}
      {panel==="plan"?<PlanForm data={data} submit={payload=>run.mutate(()=>createDeparturePlan(schoolId,payload))}/>:null}
      {panel==="office"?<OfficeRequestForm data={data} submit={payload=>run.mutate(()=>recordOfficeDepartureRequest(schoolId,payload))}/>:null}
      {error?<p className="departure-error" role="alert">{error}</p>:null}
    </section>:null}

    <section className="departure-panel"><header><div><span>Journeys</span><h2>Recent trips</h2></div><MapPin size={21}/></header>{data.trips.length?<div className="departure-trip-list">{data.trips.map(trip=><article key={trip.id}><span className={`departure-state departure-state--${trip.state}`}>{trip.state.replaceAll("_"," ")}</span><div><strong>{trip.route_name}</strong><small>{trip.service_date} · {trip.vehicle_label||trip.route_code} · {trip.collector_name}</small></div><div><strong>{trip.dropped_count}/{trip.roster_count}</strong><small>dropped</small></div></article>)}</div>:<p className="departure-empty">No trips have been created.</p>}</section>

    <section className="departure-panel"><header><div><span>Daily plans</span><h2>Upcoming handovers</h2></div><CheckCircle2 size={21}/></header>{data.plans.length?<div className="departure-plan-list">{data.plans.map(plan=><article key={plan.id}><div><strong>{plan.student_name}</strong><small>{plan.service_date} · {modeLabel(plan.mode)}{plan.collector_name?` · ${plan.collector_name}`:""}</small></div><span className={`departure-state departure-state--${plan.state}`}>{plan.state}</span>{plan.mode!=="school_transport"&&plan.state==="planned"?<button onClick={()=>run.mutate(()=>departurePlanAction(schoolId,plan.id,"ready",plan.revision,"Departure checks complete"))}>Mark ready</button>:null}{plan.mode!=="school_transport"&&plan.state==="ready"?<button className="departure-primary" onClick={()=>run.mutate(()=>recordDepartureHandover(schoolId,plan.id,{outcome:plan.mode==="independent_departure"?"departed_independently":"handed_over",authority_id:null,evidence_method:"in_person_verification",note:"Verified at departure",occurred_at:new Date().toISOString()}))}>Complete</button>:null}</article>)}</div>:<p className="departure-empty">No dated plans in the next seven days.</p>}</section>

    <section className="departure-panel"><header><div><span>Collection authority</span><h2>Current receivers</h2></div><ShieldCheck size={21}/></header>{data.authorities.length?<div className="departure-plan-list">{data.authorities.map(authority=><article key={authority.id}><div><strong>{authority.collector_name}</strong><small>{data.students.find(item=>item.id===authority.student_id)?.name} · from {authority.valid_from}</small></div><button onClick={()=>{if(window.confirm(`Revoke ${authority.collector_name}'s collection authority?`))run.mutate(()=>revokeDepartureAuthority(schoolId,authority.id,{expected_revision:authority.revision,reason:"Revoked by institution operations"}));}}>Revoke</button></article>)}</div>:<p className="departure-empty">No verified receivers.</p>}</section>
  </main></OperationsShell>;
}

function PolicyForm({data,submit}:{data:Awaited<ReturnType<typeof getDepartureWorkspace>>;submit:(payload:Record<string,unknown>)=>void}){
  return <form className="departure-form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);submit({expected_revision:data.policy.revision,enabled:form.get("enabled")==="on",enabled_modes:form.getAll("modes"),change_cutoff:value(form,"cutoff"),location_retention_hours:Number(value(form,"retention")),location_stale_seconds:Number(value(form,"stale"))});}}>
    <label className="departure-check"><input name="enabled" type="checkbox" defaultChecked={data.policy.enabled}/> Enable controlled departure</label>
    <fieldset className="departure-mode-options departure-span"><legend>Allowed arrangements</legend>{(["guardian_pickup","authorized_collector","independent_departure","school_transport","external_transport"] as DepartureMode[]).map(item=><label key={item}><input type="checkbox" name="modes" value={item} defaultChecked={data.policy.enabled_modes.includes(item)}/>{modeLabel(item)}</label>)}</fieldset>
    <label>Same-day cutoff<input name="cutoff" type="time" defaultValue={data.policy.change_cutoff.slice(0,5)} required/></label>
    <label>Location retention (hours)<input name="retention" type="number" min={1} max={168} defaultValue={data.policy.location_retention_hours} required/></label>
    <label>Stale after (seconds)<input name="stale" type="number" min={30} max={600} defaultValue={data.policy.location_stale_seconds} required/></label>
    <button className="departure-primary">Save policy</button>
  </form>;
}

function OfficeRequestForm({data,submit}:{data:Awaited<ReturnType<typeof getDepartureWorkspace>>;submit:(payload:Record<string,unknown>)=>void}){
  const initialMode=data.policy.enabled_modes.find(item=>item!=="school_transport")??"guardian_pickup";const [student,setStudent]=useState(data.students[0]?.id??"");const [mode,setMode]=useState<DepartureMode>(initialMode);const guardians=data.guardian_links.filter(item=>item.student_id===student);const authorities=data.authorities.filter(item=>item.student_id===student);
  return <form className="departure-form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);submit({student_id:student,service_date:value(form,"date"),mode,requester_person_id:value(form,"requester"),channel:value(form,"channel"),authority_id:["guardian_pickup","authorized_collector"].includes(mode)?value(form,"authority"):null,external_arrangement:mode==="external_transport"?value(form,"external"):"",reason:value(form,"reason")});}}>
    <label>Learner<select value={student} onChange={event=>setStudent(event.target.value)}>{data.students.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>
    <label>Requester<select name="requester" required>{guardians.map(item=><option value={item.person_id} key={item.id}>{item.guardian_name} · {item.relationship}</option>)}</select></label>
    <label>Received by<select name="channel"><option value="phone">Phone</option><option value="in_person">In person</option><option value="paper">Paper</option></select></label>
    <label>Date<input name="date" type="date" min={today()} defaultValue={today()} required/></label>
    <label>Arrangement<select value={mode} onChange={event=>setMode(event.target.value as DepartureMode)}>{data.policy.enabled_modes.filter(item=>item!=="school_transport").map(item=><option value={item} key={item}>{modeLabel(item)}</option>)}</select></label>
    {["guardian_pickup","authorized_collector"].includes(mode)?<label>Receiver<select name="authority" required>{authorities.map(item=><option value={item.id} key={item.id}>{item.collector_name}</option>)}</select></label>:null}
    {mode==="external_transport"?<label>Arrangement<input name="external" minLength={3} required/></label>:null}
    <label className="departure-span">Reason<textarea name="reason" minLength={3} maxLength={500} rows={3} required/></label>
    <button className="departure-primary" disabled={!guardians.length}>Record for review</button>
  </form>;
}

function AuthorityForm({data,submit}:{data:Awaited<ReturnType<typeof getDepartureWorkspace>>;submit:(payload:Record<string,unknown>)=>void}){
  const [kind,setKind]=useState<"guardian"|"other">("guardian"); const [student,setStudent]=useState(data.students[0]?.id??""); const links=data.guardian_links.filter(item=>item.student_id===student);
  return <form className="departure-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);submit({student_id:student,guardian_relationship_id:kind==="guardian"?value(f,"guardian_id"):null,collector:kind==="other"?{first_name:value(f,"first_name"),last_name:value(f,"last_name"),phone:value(f,"phone")}:null,valid_from:value(f,"valid_from"),valid_until:null,verification_method:"in_person",verification_note:value(f,"note")});}}><label>Learner<select value={student} onChange={e=>setStudent(e.target.value)}>{data.students.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Receiver type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="guardian">Linked guardian</option><option value="other">Another collector</option></select></label>{kind==="guardian"?<label>Guardian<select name="guardian_id">{links.map(item=><option value={item.id} key={item.id}>{item.guardian_name} · {item.relationship}</option>)}</select></label>:<><label>First name<input name="first_name" required/></label><label>Last name<input name="last_name"/></label><label>Phone<input name="phone" type="tel" required/></label></>}<label>Valid from<input name="valid_from" type="date" defaultValue={today()} required/></label><label className="departure-span">Verification note<input name="note" minLength={3} required/></label><button className="departure-primary">Grant collection authority</button></form>;
}

function PlanForm({data,submit}:{data:Awaited<ReturnType<typeof getDepartureWorkspace>>;submit:(payload:Record<string,unknown>)=>void}){
  const initialMode=data.policy.enabled_modes.find(item=>item!=="school_transport")??"guardian_pickup";const [student,setStudent]=useState(data.students[0]?.id??"");const [mode,setMode]=useState<DepartureMode>(initialMode);const authorities=data.authorities.filter(item=>item.student_id===student);
  const modes=data.policy.enabled_modes.filter(item=>item!=="school_transport");
  return <form className="departure-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);submit({student_id:student,service_date:value(f,"date"),mode,authority_id:["guardian_pickup","authorized_collector"].includes(mode)?value(f,"authority"):null,external_arrangement:mode==="external_transport"?value(f,"external"):"",reason:"Set by institution operations"});}}><label>Learner<select value={student} onChange={e=>setStudent(e.target.value)}>{data.students.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Date<input name="date" type="date" min={today()} defaultValue={today()} required/></label><label>Mode<select value={mode} onChange={e=>setMode(e.target.value as DepartureMode)}>{modes.map(item=><option value={item} key={item}>{modeLabel(item)}</option>)}</select></label>{["guardian_pickup","authorized_collector"].includes(mode)?<label>Receiver<select name="authority">{authorities.map(item=><option value={item.id} key={item.id}>{item.collector_name}</option>)}</select></label>:null}{mode==="external_transport"?<label>Arrangement<input name="external" required/></label>:null}<button className="departure-primary">Save departure plan</button></form>;
}
