import { describe, expect, it } from "vitest";
import type { CollectorTrip, Rider, RouteStop } from "./api";
import { coordinates, distanceMetres, riderStops, stopFocus } from "./stopFocus";
const now=Date.parse("2026-10-09T02:30:00Z");
const stops:RouteStop[]=[{id:"a",direction:"to_institution",sequence:1,name:"Castle",planned_time:null,latitude:"32.111946",longitude:"77.164802"},{id:"b",direction:"to_institution",sequence:2,name:"Road stop",planned_time:null,latitude:"32.113298",longitude:"77.168612"},{id:"school",direction:"to_institution",sequence:3,name:"Demo school",planned_time:null,latitude:"32.115339",longitude:"77.168281"}];
const rider=(id:string,stop:string,state:Rider["state"]="expected"):Rider=>({student_id:id,student_name:id,admission_number:id,state,revision:1,boarded_at:state==="boarded"?"2026-10-09T02:00:00Z":null,dropped_at:null,outcome_note:"",stop_id:stop,stop_name:stop,stop_sequence:stop==="a"?1:2,planned_time:null});
const trip={id:"trip",state:"in_progress",direction:"to_institution",stops,roster:[rider("Aarav","a"),rider("Ananya","b")],location_fresh:true,latest_location:{latitude:"32.111946",longitude:"77.164802",accuracy_metres:"10",observed_at:new Date(now).toISOString()}} as CollectorTrip;
describe("location-guided rider focus",()=>{
 it("uses the nearby pickup stop and never modifies rider outcomes",()=>{const before=JSON.stringify(trip);const focus=stopFocus(trip,riderStops(trip),now);expect(focus.nearby).toBe(true);expect(focus.group?.riders.map(r=>r.student_id)).toEqual(["Aarav"]);expect(JSON.stringify(trip)).toBe(before);});
 it("moves focus to another stop as the phone moves",()=>{const moved={...trip,latest_location:{...trip.latest_location!,latitude:stops[1]!.latitude!,longitude:stops[1]!.longitude!}};expect(stopFocus(moved,riderStops(moved),now).group?.stop.id).toBe("b");});
 it("sends boarded morning learners to school arrival, not their pickup homes",()=>{const boarded={...trip,roster:[rider("Aarav","a","boarded"),rider("Ananya","b")]};const groups=riderStops(boarded);expect(groups.map(g=>[g.stop.id,g.action])).toEqual([["b","Pickup"],["school","School arrival"]]);expect(groups[1]?.riders[0]?.student_id).toBe("Aarav");});
 it("uses a manual school arrival group if the legacy route has no school stop",()=>{const legacy={...trip,stops:[stops[0]!],roster:[rider("Aarav","a","boarded")]};expect(riderStops(legacy)[0]).toMatchObject({action:"School arrival",stop:{id:"school-arrival",latitude:null}});});
 it("shows evening boarding together, and separates home drop-offs only after departure",()=>{const outbound={...trip,direction:"from_institution" as const,stops:stops.map(s=>({...s,direction:"from_institution" as const})),roster:[rider("Aarav","a","boarded"),rider("Ananya","b","boarded")]};expect(riderStops({...outbound,state:"boarding"})[0]?.riders).toHaveLength(2);expect(riderStops(outbound).map(g=>g.riders.length)).toEqual([1,1]);});
 it.each(["stale","inaccurate","future","missing"])("does not claim a nearby stop with %s GPS",kind=>{const changed={...trip,latest_location:kind==="missing"?null:{...trip.latest_location!,accuracy_metres:kind==="inaccurate"?"200":"10",observed_at:new Date(now+(kind==="future"?60000:kind==="stale"?-100000:0)).toISOString()}};expect(stopFocus(changed,riderStops(changed),now).nearby).toBe(false);});
 it("asks for a manual choice when GPS cannot distinguish adjacent stops",()=>{const adjacent={...trip,stops:[stops[0]!,{...stops[1]!,latitude:"32.111950",longitude:"77.164810"},stops[2]!]};expect(stopFocus(adjacent,riderStops(adjacent),now).message).toMatch(/close together/);});
 it("keeps next unresolved stop visible when the phone is far away",()=>{const away={...trip,latest_location:{...trip.latest_location!,latitude:"32.2"}};const focus=stopFocus(away,riderStops(away),now);expect(focus.nearby).toBe(false);expect(focus.group?.stop.id).toBe("a");expect(focus.distance).toBeGreaterThan(1000);});
 it("excludes resolved learners but retains concerns",()=>{const changed={...trip,roster:[rider("Aarav","a","dropped"),rider("Ananya","b","exception"),rider("Other","a","not_riding")]};expect(riderStops(changed).flatMap(g=>g.riders).map(r=>r.student_id)).toEqual(["Ananya"]);});
 it("validates coordinates without treating null as zero",()=>{expect(coordinates({latitude:null,longitude:null})).toBeNull();expect(coordinates({latitude:91,longitude:77})).toBeNull();expect(coordinates({latitude:0,longitude:0})).toEqual({latitude:0,longitude:0});expect(distanceMetres({latitude:0,longitude:0},{latitude:0,longitude:0})).toBe(0);});
});
