import { ArrowRight, LoaderCircle, Sparkles } from "lucide-react";
import { useState, type FormEvent } from "react";
import { applyQuickStart } from "./api";

const iso=(date:Date)=>date.toISOString().slice(0,10);
function academicYear(date=new Date()){const year=date.getMonth()>=3?date.getFullYear():date.getFullYear()-1;return `${year}-${String(year+1).slice(-2)}`;}
function codeFor(name:string,index:number){const value=name.toUpperCase().replace(/[^A-Z0-9]+/g,"_").replace(/^_|_$/g,"").slice(0,12);return value || `SUBJ_${index+1}`;}
function field(form:FormData,name:string){const value=form.get(name);return typeof value==="string"?value:"";}

export function QuickStartForm({schoolId,cohortLabel,defaults,onDone}:{schoolId:string;cohortLabel:string;defaults:string[];onDone:()=>Promise<void>}){
  const today=new Date();const yearEnd=new Date(today);yearEnd.setFullYear(today.getFullYear()+1);
  const [subjects,setSubjects]=useState(defaults.join(", "));const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const names=subjects.split(",").map(value=>value.trim()).filter(Boolean);
    try{await applyQuickStart(schoolId,{academic_year:field(form,"academic_year"),term_name:field(form,"term_name"),starts_on:field(form,"starts_on"),ends_on:field(form,"ends_on"),grade_or_program:field(form,"grade_or_program"),section:field(form,"section"),subjects:names.map((name,index)=>({code:codeFor(name,index),name,short_name:name.slice(0,40)})),attendance_threshold:Number(field(form,"attendance_threshold")),medical_document_after_days:Number(field(form,"medical_document_after_days")),contact_name:field(form,"contact_name"),contact_phone:field(form,"contact_phone"),contact_email:field(form,"contact_email"),teaching_days:[1,2,3,4,5,6].filter(day=>form.has(`day_${day}`)),starts_at:field(form,"starts_at"),ends_at:field(form,"ends_at")});await onDone();}
    catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
  return <section className="activation-card activation-quick"><header><span><Sparkles/></span><div><h2>Quick setup</h2><small>Term, {cohortLabel.toLowerCase()}, subjects, attendance and timetable.</small></div></header><form onSubmit={submit}>
    <fieldset><legend>Academic structure</legend><div className="activation-form-grid"><label>Academic year<input name="academic_year" defaultValue={academicYear(today)} pattern="\d{4}-\d{2}" required/></label><label>Term name<input name="term_name" defaultValue="Term 1" required/></label><label>Starts on<input type="date" name="starts_on" defaultValue={iso(today)} required/></label><label>Ends on<input type="date" name="ends_on" defaultValue={iso(yearEnd)} required/></label><label>{cohortLabel} name<input name="grade_or_program" placeholder="e.g. Class 6 or Foundation" required/></label><label>Section<input name="section" defaultValue="A" required/></label></div><label>Subjects or courses <span>(comma separated)</span><textarea value={subjects} onChange={event=>setSubjects(event.target.value)} rows={2} required/></label></fieldset>
    <fieldset><legend>Attendance and first period</legend><div className="activation-form-grid"><label>Minimum attendance %<input type="number" name="attendance_threshold" min="1" max="100" defaultValue="85" required/></label><label>Document after days<input type="number" name="medical_document_after_days" min="0" max="30" defaultValue="2" required/></label><label>Period starts<input type="time" name="starts_at" defaultValue="09:00" required/></label><label>Period ends<input type="time" name="ends_at" defaultValue="09:45" required/></label></div><div className="activation-days" role="group" aria-label="Teaching days">{[[1,"Mon"],[2,"Tue"],[3,"Wed"],[4,"Thu"],[5,"Fri"],[6,"Sat"]].map(([day,label])=><label key={day}><input type="checkbox" name={`day_${day}`} defaultChecked={day!==6}/><span>{label}</span></label>)}</div></fieldset>
    <fieldset><legend>Fallback contact</legend><div className="activation-form-grid"><label>Responsible contact<input name="contact_name" placeholder="Office or owner name" required/></label><label>Phone<input name="contact_phone" inputMode="tel"/></label><label className="activation-wide">Email<input type="email" name="contact_email"/></label></div><small>Phone or email required for service outages.</small></fieldset>
    {error?<p className="activation-alert" role="alert">{error}</p>:null}<button className="activation-primary" disabled={busy||!subjects.trim()}>{busy?<><LoaderCircle className="auth-spin"/>Creating foundation…</>:<>Create and review records <ArrowRight/></>}</button>
  </form></section>;
}
