-- Durable attendance commands, correction history, and replayable event delivery.

ALTER TABLE attendance_records
  ADD COLUMN IF NOT EXISTS revision integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS source_request_id uuid;

ALTER TABLE event_outbox
  ADD COLUMN IF NOT EXISTS sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS published_by varchar(120),
  ADD COLUMN IF NOT EXISTS notification_user_ids uuid[] NOT NULL DEFAULT ARRAY[]::uuid[],
  ADD COLUMN IF NOT EXISTS notification_payload jsonb,
  ADD COLUMN IF NOT EXISTS expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days');

CREATE UNIQUE INDEX IF NOT EXISTS event_outbox_sequence_idx
  ON event_outbox(sequence);
CREATE INDEX IF NOT EXISTS event_outbox_replay_idx
  ON event_outbox(sequence, created_at)
  WHERE published_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS event_outbox_expiry_idx
  ON event_outbox(expires_at);

CREATE TABLE IF NOT EXISTS attendance_registers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  class_section_id uuid NOT NULL REFERENCES class_sections(id) ON DELETE CASCADE,
  term_id uuid NOT NULL REFERENCES academic_terms(id) ON DELETE RESTRICT,
  date date NOT NULL,
  state varchar(16) NOT NULL DEFAULT 'draft' CHECK (state IN ('draft', 'submitted', 'locked')),
  revision integer NOT NULL DEFAULT 0 CHECK (revision >= 0),
  submitted_by uuid REFERENCES users(id) ON DELETE SET NULL,
  submitted_at timestamptz,
  locked_by uuid REFERENCES users(id) ON DELETE SET NULL,
  locked_at timestamptz,
  reopened_by uuid REFERENCES users(id) ON DELETE SET NULL,
  reopened_at timestamptz,
  reopen_reason varchar(500),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((submitted_at IS NULL) = (submitted_by IS NULL)),
  CHECK ((locked_at IS NULL) = (locked_by IS NULL)),
  CHECK (reopen_reason IS NULL OR length(btrim(reopen_reason)) >= 3),
  UNIQUE (class_section_id, term_id, date)
);
CREATE INDEX IF NOT EXISTS attendance_registers_school_date_idx
  ON attendance_registers(school_id, date DESC, class_section_id);

CREATE TABLE IF NOT EXISTS attendance_submissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  class_section_id uuid NOT NULL REFERENCES class_sections(id) ON DELETE CASCADE,
  term_id uuid NOT NULL REFERENCES academic_terms(id) ON DELETE RESTRICT,
  date date NOT NULL,
  submitted_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  idempotency_key varchar(128) NOT NULL,
  request_hash char(64) NOT NULL,
  request_id uuid NOT NULL,
  register_revision integer NOT NULL CHECK (register_revision > 0),
  records_count integer NOT NULL CHECK (records_count > 0),
  changed_count integer NOT NULL CHECK (changed_count >= 0),
  result_status integer NOT NULL DEFAULT 200 CHECK (result_status BETWEEN 200 AND 599),
  result_body jsonb NOT NULL DEFAULT '{}'::jsonb,
  completed_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (changed_count <= records_count),
  UNIQUE (school_id, submitted_by, idempotency_key)
);
CREATE INDEX IF NOT EXISTS attendance_submissions_register_idx
  ON attendance_submissions(class_section_id, date DESC, created_at DESC);

CREATE TABLE IF NOT EXISTS attendance_record_revisions (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  attendance_record_id uuid NOT NULL REFERENCES attendance_records(id) ON DELETE RESTRICT,
  attendance_submission_id uuid REFERENCES attendance_submissions(id) ON DELETE RESTRICT,
  attendance_register_id uuid REFERENCES attendance_registers(id) ON DELETE RESTRICT,
  school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  student_id uuid NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
  class_section_id uuid NOT NULL REFERENCES class_sections(id) ON DELETE RESTRICT,
  date date NOT NULL,
  previous_status varchar(16) CHECK (previous_status IS NULL OR previous_status IN ('present', 'absent', 'late', 'excused', 'half_day')),
  new_status varchar(16) NOT NULL CHECK (new_status IN ('present', 'absent', 'late', 'excused', 'half_day')),
  previous_remarks varchar(500),
  new_remarks varchar(500) NOT NULL DEFAULT '',
  previous_check_in_at timestamptz,
  new_check_in_at timestamptz,
  previous_check_out_at timestamptz,
  new_check_out_at timestamptz,
  reason varchar(500) NOT NULL,
  changed_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  request_id uuid NOT NULL,
  register_revision integer NOT NULL CHECK (register_revision > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (length(btrim(reason)) >= 3),
  UNIQUE (request_id, attendance_record_id)
);
CREATE INDEX IF NOT EXISTS attendance_revisions_student_date_idx
  ON attendance_record_revisions(student_id, date DESC, id DESC);
CREATE INDEX IF NOT EXISTS attendance_revisions_register_idx
  ON attendance_record_revisions(class_section_id, date DESC, register_revision);

ALTER TABLE schools ADD COLUMN IF NOT EXISTS timezone varchar(64) NOT NULL DEFAULT 'Asia/Kolkata';

CREATE TABLE IF NOT EXISTS school_calendar_days (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  date date NOT NULL,
  is_instructional boolean NOT NULL,
  label varchar(160) NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (school_id, date)
);
CREATE INDEX IF NOT EXISTS school_calendar_instructional_idx
  ON school_calendar_days(school_id, date) WHERE is_instructional;

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS dedupe_key text;
CREATE UNIQUE INDEX IF NOT EXISTS notifications_recipient_dedupe_idx
  ON notifications(recipient_id, dedupe_key)
  WHERE dedupe_key IS NOT NULL;

-- Index every attendance hot-path equality key and frequently traversed relation.
CREATE INDEX IF NOT EXISTS attendance_class_date_student_idx
  ON attendance_records(class_section_id, date DESC, student_id);
CREATE INDEX IF NOT EXISTS enrollments_class_term_active_idx
  ON enrollments(class_section_id, term_id, student_id)
  WHERE is_active;
CREATE INDEX IF NOT EXISTS guardian_relationships_student_guardian_idx
  ON guardian_relationships(student_id, guardian_id);
CREATE INDEX IF NOT EXISTS school_memberships_school_role_active_idx
  ON school_memberships(school_id, role, user_id)
  WHERE is_active;
CREATE INDEX IF NOT EXISTS timetable_teacher_term_idx
  ON timetable_slots(teacher_user_id, term_id, class_section_id)
  WHERE teacher_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS attendance_registers_open_idx
  ON attendance_registers(school_id, date, state, class_section_id)
  WHERE state <> 'locked';
CREATE INDEX IF NOT EXISTS notifications_unread_recipient_idx
  ON notifications(recipient_id, created_at DESC) WHERE read_at IS NULL;
CREATE INDEX IF NOT EXISTS leave_documents_request_idx ON leave_documents(leave_request_id);
CREATE INDEX IF NOT EXISTS leave_audits_request_time_idx ON leave_audits(leave_request_id, created_at);
CREATE INDEX IF NOT EXISTS auth_sessions_user_expiry_idx ON auth_sessions(user_id, expires_at DESC);
CREATE INDEX IF NOT EXISTS ai_messages_conversation_time_idx ON ai_messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS audit_events_school_time_idx ON audit_events(school_id, created_at DESC);
CREATE INDEX IF NOT EXISTS audit_events_target_time_idx ON audit_events(target_type, target_id, created_at DESC);

-- Defense in depth: API authorization is the primary access boundary, while
-- deferred constraint triggers make cross-school relationship corruption
-- impossible even for server-side maintenance jobs and future importers.
CREATE OR REPLACE FUNCTION validate_school_relationships()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  expected_school uuid;
  related_school uuid;
BEGIN
  IF TG_TABLE_NAME = 'enrollments' THEN
    SELECT school_id INTO expected_school FROM students WHERE id=NEW.student_id;
    SELECT school_id INTO related_school FROM class_sections WHERE id=NEW.class_section_id;
    IF expected_school IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Enrollment student and class must belong to one school' USING ERRCODE='23514'; END IF;
    SELECT school_id INTO related_school FROM academic_terms WHERE id=NEW.term_id;
    IF expected_school IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Enrollment student and term must belong to one school' USING ERRCODE='23514'; END IF;
  ELSIF TG_TABLE_NAME = 'subject_attendance' THEN
    SELECT school_id INTO expected_school FROM students WHERE id=NEW.student_id;
    SELECT school_id INTO related_school FROM subjects WHERE id=NEW.subject_id;
    IF expected_school IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Subject attendance student and subject must belong to one school' USING ERRCODE='23514'; END IF;
    SELECT school_id INTO related_school FROM academic_terms WHERE id=NEW.term_id;
    IF expected_school IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Subject attendance student and term must belong to one school' USING ERRCODE='23514'; END IF;
  ELSIF TG_TABLE_NAME = 'attendance_records' THEN
    SELECT school_id INTO expected_school FROM students WHERE id=NEW.student_id;
    SELECT school_id INTO related_school FROM class_sections WHERE id=NEW.class_section_id;
    IF expected_school IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Attendance student and class must belong to one school' USING ERRCODE='23514'; END IF;
  ELSIF TG_TABLE_NAME = 'timetable_slots' THEN
    SELECT school_id INTO expected_school FROM class_sections WHERE id=NEW.class_section_id;
    SELECT school_id INTO related_school FROM academic_terms WHERE id=NEW.term_id;
    IF expected_school IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Timetable class and term must belong to one school' USING ERRCODE='23514'; END IF;
    IF NEW.subject_id IS NOT NULL THEN
      SELECT school_id INTO related_school FROM subjects WHERE id=NEW.subject_id;
      IF expected_school IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Timetable subject must belong to the class school' USING ERRCODE='23514'; END IF;
    END IF;
    IF NEW.teacher_user_id IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM school_memberships m WHERE m.school_id=expected_school
        AND m.user_id=NEW.teacher_user_id AND m.role IN ('staff','admin') AND m.is_active
    ) THEN RAISE EXCEPTION 'Timetable teacher must be active in the class school' USING ERRCODE='23514'; END IF;
  ELSIF TG_TABLE_NAME = 'leave_requests' THEN
    SELECT school_id INTO expected_school FROM students WHERE id=NEW.student_id;
    SELECT school_id INTO related_school FROM academic_terms WHERE id=NEW.term_id;
    IF expected_school IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Leave student and term must belong to one school' USING ERRCODE='23514'; END IF;
  ELSIF TG_TABLE_NAME = 'diary_items' THEN
    SELECT school_id INTO related_school FROM class_sections WHERE id=NEW.class_section_id;
    IF NEW.school_id IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Diary class must belong to its school' USING ERRCODE='23514'; END IF;
    SELECT school_id INTO related_school FROM academic_terms WHERE id=NEW.term_id;
    IF NEW.school_id IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Diary term must belong to its school' USING ERRCODE='23514'; END IF;
    IF NEW.subject_id IS NOT NULL THEN
      SELECT school_id INTO related_school FROM subjects WHERE id=NEW.subject_id;
      IF NEW.school_id IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Diary subject must belong to its school' USING ERRCODE='23514'; END IF;
    END IF;
  ELSIF TG_TABLE_NAME IN ('attendance_registers', 'attendance_submissions') THEN
    SELECT school_id INTO related_school FROM class_sections WHERE id=NEW.class_section_id;
    IF NEW.school_id IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Attendance register class must belong to its school' USING ERRCODE='23514'; END IF;
    SELECT school_id INTO related_school FROM academic_terms WHERE id=NEW.term_id;
    IF NEW.school_id IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Attendance register term must belong to its school' USING ERRCODE='23514'; END IF;
  ELSIF TG_TABLE_NAME = 'attendance_record_revisions' THEN
    SELECT school_id INTO related_school FROM students WHERE id=NEW.student_id;
    IF NEW.school_id IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Attendance revision student must belong to its school' USING ERRCODE='23514'; END IF;
    SELECT school_id INTO related_school FROM class_sections WHERE id=NEW.class_section_id;
    IF NEW.school_id IS DISTINCT FROM related_school THEN RAISE EXCEPTION 'Attendance revision class must belong to its school' USING ERRCODE='23514'; END IF;
  END IF;
  RETURN NEW;
END $$;

DO $$
DECLARE
  relation_name text;
  trigger_name text;
BEGIN
  FOREACH relation_name IN ARRAY ARRAY[
    'enrollments','subject_attendance','attendance_records','timetable_slots',
    'leave_requests','diary_items','attendance_registers','attendance_submissions',
    'attendance_record_revisions'
  ] LOOP
    trigger_name := 'validate_' || relation_name || '_school';
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname=trigger_name) THEN
      EXECUTE format(
        'CREATE CONSTRAINT TRIGGER %I AFTER INSERT OR UPDATE ON %I DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION validate_school_relationships()',
        trigger_name, relation_name
      );
    END IF;
  END LOOP;
END $$;

REVOKE ALL ON FUNCTION validate_school_relationships() FROM PUBLIC;

-- The browser never talks to Supabase's Data API. Keep public tables closed to
-- anon/authenticated roles when those Supabase roles exist, while the server's
-- direct database role remains the sole application data path.
DO $$
DECLARE
  table_name text;
  protected_tables text[] := ARRAY[
    'users', 'schools', 'school_memberships', 'students', 'parents',
    'guardian_relationships', 'academic_terms', 'class_sections', 'enrollments',
    'subjects', 'subject_attendance', 'attendance_records', 'gate_events',
    'timetable_slots', 'attendance_policies', 'leave_requests', 'leave_documents',
    'leave_audits', 'diary_items', 'diary_acknowledgements', 'homework_completions',
    'diary_notes', 'notifications', 'school_contacts', 'auth_sessions',
    'audit_events', 'ai_conversations', 'ai_messages', 'api_rate_limit_buckets',
    'event_outbox', 'attendance_registers', 'attendance_submissions',
    'attendance_record_revisions', 'school_calendar_days', 'node_schema_migrations'
  ];
BEGIN
  FOREACH table_name IN ARRAY protected_tables LOOP
    IF to_regclass(format('public.%I', table_name)) IS NOT NULL THEN
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon', table_name);
      END IF;
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        EXECUTE format('REVOKE ALL ON TABLE public.%I FROM authenticated', table_name);
      END IF;
    END IF;
  END LOOP;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM authenticated';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM authenticated';
  END IF;
END $$;
