import { apiFetch } from "../../lib/api";

export type AssessmentStatus = "draft"|"scheduled"|"marking"|"submitted"|"moderated"|"published"|"cancelled";
export type ResultOutcome = "unrecorded"|"scored"|"absent"|"exempt"|"withheld"|"not_evaluated";
export interface AssessmentCycle { id:string; term_id:string; name:string; code:string; starts_on:string; ends_on:string; status:string; result_label:string; revision:number; term_name:string; academic_year:string; assessment_count:number; published_count:number }
export interface AssessmentSummary { id:string; cycle_id:string; class_section_id:string; subject_id:string; title:string; assessment_kind:string; maximum_marks:string; weight_percent:string|null; scheduled_at:string|null; duration_minutes:number|null; venue:string; instructions:string; evidence_requirement:"none"|"optional"|"required"; status:AssessmentStatus; revision:number; moderation_note:string; cycle_name:string; subject_name:string; color:string; icon:string; class_name:string; examiner_user_id:string; examiner_name:string; moderator_user_id:string; moderator_name:string; roster_count:number; unrecorded_count:number; publication_sequence:number }
export interface AssessmentResult { id:string; student_id:string; outcome:ResultOutcome; marks:string|null; grade:string; feedback:string; revision:number; first_name:string; last_name:string; admission_number:string; roll_number:number|null; evidence_count:number; evidence:Array<{id:string;original_name:string;content_type:string;size_bytes:number;uploaded_at:string}>|null }
export interface AssessmentDetail { assessment:AssessmentSummary & {term_id:string}; results:AssessmentResult[]; publications:Array<{id:string;sequence:number;reason:string;published_at:string;source_revision:number}>; viewer_role:"admin"|"examiner"|"moderator" }
export interface AdminAssessmentWorkspace { mode:"admin"; cycles:AssessmentCycle[]; assessments:AssessmentSummary[]; references:{ terms:Array<{id:string;name:string;academic_year:string;starts_on:string;ends_on:string}>; classes:Array<{id:string;name:string;academic_year:string}>; subjects:Array<{id:string;name:string;color:string;icon:string}>; staff:Array<{id:string;first_name:string;last_name:string;designation:string|null}> } }
export interface StaffAssessmentWorkspace { mode:"staff"; cycles:AssessmentCycle[]; assessments:AssessmentSummary[] }
export type AssessmentWorkspace=AdminAssessmentWorkspace|StaffAssessmentWorkspace;
export interface FamilyResults { student:{id:string;first_name:string;last_name:string;admission_number:string;class_name:string|null}; results:Array<{id:string;title:string;assessment_kind:string;maximum_marks:string;scheduled_at:string|null;subject_name:string;color:string;icon:string;cycle_name:string;publication_id:string;sequence:number;published_at:string;outcome:Exclude<ResultOutcome,"unrecorded">;marks:string|null;grade:string;feedback:string}> }

const root=(schoolId:string,path="")=>`/api/v1/schools/${encodeURIComponent(schoolId)}/assessments${path}`;
export const getAssessmentWorkspace=(schoolId:string)=>apiFetch<AssessmentWorkspace>(root(schoolId,"/workspace/"));
export const getAssessmentDetail=(schoolId:string,id:string)=>apiFetch<AssessmentDetail>(root(schoolId,`/${id}/`));
export const createAssessmentCycle=(schoolId:string,input:Record<string,unknown>)=>apiFetch<AssessmentCycle>(root(schoolId,"/cycles/"),{method:"POST",body:JSON.stringify(input)});
export const createAssessment=(schoolId:string,input:Record<string,unknown>)=>apiFetch<AssessmentSummary>(root(schoolId),{method:"POST",body:JSON.stringify(input)});
export const assessmentAction=(schoolId:string,id:string,action:string,expectedRevision:number,note="")=>apiFetch<AssessmentSummary>(root(schoolId,`/${id}/actions/${action}/`),{method:"POST",body:JSON.stringify({expected_revision:expectedRevision,note})});
export const saveAssessmentResults=(schoolId:string,id:string,expectedAssessmentRevision:number,results:Array<{result_id:string;outcome:Exclude<ResultOutcome,"unrecorded">;marks:number|null;grade:string;feedback:string;expected_revision:number;reason:string}>)=>apiFetch<AssessmentSummary>(root(schoolId,`/${id}/results/`),{method:"POST",body:JSON.stringify({expected_assessment_revision:expectedAssessmentRevision,results})});
export async function uploadAssessmentEvidence(schoolId:string,assessmentId:string,resultId:string,file:File,reason:string){const body=new FormData();body.set("file",file);body.set("reason",reason);return apiFetch(root(schoolId,`/${assessmentId}/results/${resultId}/evidence/`),{method:"POST",body});}
export const getFamilyResults=(schoolId:string,studentId:string)=>apiFetch<FamilyResults>(`${root(schoolId,"/family/")}?student_id=${encodeURIComponent(studentId)}`);
