import type {ReactNode} from 'react';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {MemoryRouter,Route,Routes} from 'react-router-dom';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import StudentPulsePage,{PulseOverview} from './StudentPulsePage';
import type {PulseDetail,PulseList,PulseSignal} from './api';
const api=vi.hoisted(()=>({getPulse:vi.fn(),getPulseDetail:vi.fn(),savePulse:vi.fn()}));
vi.mock('./api',async()=>({...await vi.importActual('./api'),...api}));
vi.mock('../auth/AuthContext',()=>({useOptionalAuth:()=>({status:'authenticated',user:{id:'owner',active_school_id:'school'},memberships:[]})}));
vi.mock('../../pages/operations/OperationsShell',()=>({OperationsShell:({children}:{children:ReactNode})=><main>{children}</main>}));
const signal=(student_id='student',student_name='C. Prasik'):PulseSignal=>({student_id,student_name,class_id:'class',class_name:'Class 10A',term_id:'term',term_name:'Term 1',subject_id:'math',subject_name:'Mathematics',held:9,attended:3,excused:0,eligible:9,missed:6,percentage:100/3,other_percentage:100,gap:200/3,flagged:true,followup:null,subjects:[{subject_id:'math',name:'Mathematics',held:9,attended:3,excused:0,eligible:9,percentage:100/3},{subject_id:'english',name:'English',held:12,attended:12,excused:0,eligible:12,percentage:100}]});
const data=():PulseList=>({school_id:'school',today:'2026-10-08',generated_at:'2026-10-08T10:00:00Z',source:'recorded_term_totals',signals:[signal()]});
const detail=():PulseDetail=>({signal:signal(),followup:null,owners:[{id:'owner',name:'Class Teacher'}],history:[]});
function open(path='/principal/student-pulse/student/term/math') {const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><Routes><Route path="/principal/student-pulse" element={<StudentPulsePage/>}/><Route path="/principal/student-pulse/:studentId/:termId/:subjectId" element={<StudentPulsePage/>}/></Routes></MemoryRouter></QueryClientProvider>);}
afterEach(cleanup);
beforeEach(()=>{api.getPulse.mockResolvedValue(data());api.getPulseDetail.mockResolvedValue(detail());api.savePulse.mockReset();});
describe('Student Pulse screens',()=>{
 it('shows named insight and real source limits',async()=>{open('/principal/student-pulse');expect(await screen.findByRole('heading',{name:'C. Prasik'})).toBeInTheDocument();expect(screen.getByText(/Based on recorded term totals/)).toBeInTheDocument();expect(screen.getByRole('link',{name:'Review pattern'})).toHaveAttribute('href','/principal/student-pulse/student/term/math');});
 it('supports filtering and honest empty states',async()=>{open('/principal/student-pulse');await screen.findByText('C. Prasik');fireEvent.change(screen.getByRole('textbox',{name:'Search student, subject or class'}),{target:{value:'unmatched'}});expect(screen.getByRole('heading',{name:'No matching insights'})).toBeInTheDocument();});
 it('shows shared subject patterns only at three students',()=>{const list=data();list.signals.push(signal('two','Riya'),signal('three','Aman'));render(<MemoryRouter><PulseOverview data={list} base="/principal/student-pulse" onRefresh={()=>{}}/></MemoryRouter>);fireEvent.click(screen.getByRole('button',{name:'Class patterns'}));expect(screen.getByRole('heading',{name:'3 students have lower Mathematics attendance'})).toBeInTheDocument();});
 it('does not invent lesson sequences or motives',async()=>{open();await screen.findByRole('heading',{name:'C. Prasik'});expect(screen.getByText(/Dated period records are not available/)).toBeInTheDocument();expect(screen.getByText(/not evidence of deliberate skipping/)).toBeInTheDocument();});
 it('requires a human records review before submitting',async()=>{open();await screen.findByRole('heading',{name:'C. Prasik'});fireEvent.click(screen.getByRole('button',{name:'Plan a check-in'}));expect(screen.getByRole('button',{name:'Create staff follow-up'})).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));expect(screen.getByRole('button',{name:'Create staff follow-up'})).toBeEnabled();expect(api.savePulse).not.toHaveBeenCalled();});
 it('surfaces rejected writes and offers a conflict refresh',async()=>{api.savePulse.mockRejectedValue(new Error('This follow-up changed. Refresh before saving.'));open();await screen.findByRole('heading',{name:'C. Prasik'});fireEvent.click(screen.getByRole('button',{name:'Plan a check-in'}));fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Create staff follow-up'}));expect(await screen.findByRole('alert')).toHaveTextContent('follow-up changed');expect(screen.getByRole('button',{name:'Refresh latest follow-up'})).toBeInTheDocument();});
 it('persists the command and opens progress only after success',async()=>{const saved:PulseDetail={...detail(),followup:{id:'followup',owner_user_id:'owner',owner_name:'Class Teacher',state:'check_in',action:'private_check_in',due_on:'2026-10-08',outcome:null,revision:1,baseline_held:9,baseline_attended:3,baseline_excused:0,created_at:'2026-10-08',updated_at:'2026-10-08'}};api.savePulse.mockResolvedValue(saved);open();await screen.findByRole('heading',{name:'C. Prasik'});fireEvent.click(screen.getByRole('button',{name:'Plan a check-in'}));fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Create staff follow-up'}));await waitFor(()=>expect(api.savePulse).toHaveBeenCalledWith('school','student/term/math',expect.objectContaining({records_reviewed:true,expected_revision:0,owner_user_id:'owner'})));expect(await screen.findByRole('heading',{name:'Follow-up history'})).toBeInTheDocument();expect(screen.getByText(/No additional eligible sessions/)).toBeInTheDocument();});
 it('requires an outcome when a reviewer closes an existing follow-up',async()=>{api.getPulseDetail.mockResolvedValue({...detail(),followup:{id:'f',owner_user_id:'owner',owner_name:'Class Teacher',state:'monitoring',action:'private_check_in',due_on:'2026-10-08',outcome:null,revision:2,baseline_held:9,baseline_attended:3,baseline_excused:0,created_at:'2026-10-08',updated_at:'2026-10-08'}});open();await screen.findByRole('heading',{name:'C. Prasik'});fireEvent.click(screen.getByRole('button',{name:'Plan a check-in'}));fireEvent.change(screen.getByRole('combobox',{name:'Follow-up status'}),{target:{value:'resolved'}});expect(screen.getByRole('combobox',{name:'Human-recorded outcome'})).toBeRequired();});
});
